### ISSUE TITLE
Automatically create collapsed/implicit/shortcut reference links

### ISSUE THREAD

**Issue by davidtheclark** [remarkjs/remark-reference-links#10]
### Subject of the feature

If it's possible, I'd like to automatically create link references in the following style:

```markdown
See [spot] run.
<!-- And/or ... -->
See [dog][] jump.

[spot]: https...
[dog]: https...
```

In the CommonMark spec I see this syntax referred to as [shortcut reference link](https://spec.commonmark.org/0.29/#shortcut-reference-link) — if there is no `[]` — and [collapsed reference link](https://spec.commonmark.org/0.29/#collapsed-reference-link) — if there is a `[]`. In the [canonical Markdown description](https://daringfireball.net/projects/markdown/syntax), I don't see any equivalent of the shortcut reference link, but the collapsed reference link is called "implicit name link shortcut."

I don't think I can do this with either remark-reference-links or [remark-def-split](https://github.com/remarkjs/remark-defsplit). So this is a feature idea.

I am worried this can't be implemented, though, because the link label (`spot` and `dog` above) can include any [static phrasing content](https://github.com/syntax-tree/mdast#staticphrasingcontent) but I don't see a way for the mdast [Definition](https://github.com/syntax-tree/mdast#definition) node to store and render a complex label (or identifier). Here's an example I'm failing to figure out how to handle:

```markdown
See [your **favorite** dog] run.

[your **favorite** dog]: https...
```

Do you think it's possible with the existing AST to perform a full transformation of all links to shortcuts or collapsed reference links? Or are we limited by the flexibility of label content, and could only transform links with simple text labels?

**Comment by wooorm** [comment]
Indeed, there are three types of reference links. Shortcuts (`[asd]`), collapsed (`[asd][]`), and full (`[asd][fgh]`). It’s unfortunate that shortcuts exist, they are extremely unclear. For example, adding `[x]: example.com` to a GFM document disables task lists 🤯. I strongly recommend against using shortcuts, and remark-lint warns about them I believe? To either escape one of the brackets, or add `[]`.

Reference links are also fragile in CommonMark: `[[asd]](https://link.com?)` turns into a link for `[asd]` when it is defined. When it isn’t, it turns into a link to `link.com`. As definitions can be defined anywhere in a document, it makes it impossible to parse Markdown in a nice stream.

I personally do enjoy using collapsed and full reference links, so I see some use in your request. But indeed, the `[your **favorite** dog]` example is annoying. As link labels can be super long, and indeed contain static phrasing content... Say a link label was 999 characters long, would you still want a definition label with the same length? Wouldn’t a short label be better?

**Comment by davidtheclark** [comment]
I've had only happy times with shortcut links, despite their theoretical flaws — I guess I've been lucky 😄 

> Say a link label was 999 characters long, would you still want a definition label with the same length?

Personally, I wouldn't want a link label that long any more than I'd want a definition label that long.

Sounds like I'm right that the static phrasing content throws a real wrench in the possibility ...

The only thing I really don't like about numbered references & definitions is that — when systematically applied, always counting from the document's top to its bottom — this means the addition or removal of a link in the middle of the document will result in changes to links & definitions all over the document, making a nasty diff. I can live with that, though.

**Comment by wooorm** [comment]
A different idea for numbers/letters/other orders: what if we “hash” the paragraph? E.g., first letter of first three and last three words:

```
Lorem ipsum dolor sit amet[1], consectetur adipisicing elit[2].
```

Yields:

```
Lorem ipsum dolor sit amet[lidcae-1], consectetur adipisicing elit[lidcae-2].
```

That should result in cleaner diffs

**Comment by davidtheclark** [comment]
Yeah, I did think about that, too. Considering the tradeoff of markdown legibility vs diff cleanliness, I might choose the legibility of the markdown, and so favor the bare numbers instead of potentially confusing-looking text 😬
