### ISSUE TITLE
Superfluous newlines added to Markdown references.

### ISSUE THREAD

**Issue by seth-brown** [remarkjs/remark-reference-links#9]
### Superfluous newlines added to Markdown references.

Thanks for the great work on this plugin! Perhaps this is a bug or just correct behavior I wasn't expecting. When `remark-reference-links` is used to convert inline links to references, it adds extra newline character after every reference.

### Your environment

*   **OS**: OSX 10.15.4
*   **Packages**:  {"remark": "12.0.0", "remark-inline-links": "4.0.0", "remark-parse": "8.0.2", "unified": "9.0.0"}
*   **Env**: node v14.1.0

### Steps to reproduce

Here's a minimal working example:

```
const remark = require('remark')
const refLinks = require('remark-reference-links')

const mdInline = "The quick brown [fox](http://en.wikipedia.org/wiki/Fox) jumped over the lazy [dog](http://en.wikipedia.org/wiki/Dog)."

remark()
  .use(refLinks)
  .process(mdInline, (err, d) => { console.log(d.contents) })
```

The output of the code above looks like this:
```
'The quick brown [fox][1] jumped over the lazy [dog][2].\n' +
'\n' +
'[1]: http://en.wikipedia.org/wiki/Fox\n' +
'\n' +
'[2]: http://en.wikipedia.org/wiki/Dog\n'
```

### Expected behaviour

The expected behaviour is no newline characters after the final reference and no newline characters between reference lines. Here's what I would have expected:

```
'The quick brown [fox][1] jumped over the lazy [dog][2].\n' +
'\n' +
'[1]: http://en.wikipedia.org/wiki/Fox\n' +
'[2]: http://en.wikipedia.org/wiki/Dog'
```

### Actual behaviour

```
'The quick brown [fox][1] jumped over the lazy [dog][2].\n' +
'\n' +
'[1]: http://en.wikipedia.org/wiki/Fox\n' +
'\n' +
'[2]: http://en.wikipedia.org/wiki/Dog\n'
```

**Comment by wooorm** [comment]
Hi Seth! 👋 This is unrelated to this project, but instead has to do with how blocks (headings, thematic breaks, etc, but also these resource definitions) are serialized by `remark-stringify`.

We decided on one single style: blank lines between all blocks. Be it paragraphs, or definitions. Is this something you cannot live with, or is it perhaps a style you could get used to? 😉

**Comment by seth-brown** [comment]
👋 Hi Titus, thanks for the reply and explanation. My main issue is that many of the markdown documents I work on can have a large number of links, which makes the reference section extremely long when each reference has a newline above and below it. However, the current style is definitely something I can live with. Thanks again.

**Comment by wooorm** [comment]
Right, I understand. I think a single rule without exceptions is easiest, but if the style is not for you, prettier formats markdown without blank lines between definitions!
